// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Verto.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250505150107_AddNewSliderTexts")]
    partial class AddNewSliderTexts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HomePageContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CircleIconsImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiscoverImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExploreImage1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExploreImage2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExploreImage3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeatureImage1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeatureImage2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeatureImage3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeatureImage4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HomePageContents");
                });

            modelBuilder.Entity("HomePageContent", b =>
                {
                    b.OwnsMany("Text", "SliderTexts", b1 =>
                        {
                            b1.Property<int>("HomePageContentId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Description")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Title")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("HomePageContentId", "Id");

                            b1.ToTable("SliderTexts");

                            b1.WithOwner("HomePageContent")
                                .HasForeignKey("HomePageContentId");

                            b1.Navigation("HomePageContent");
                        });

                    b.Navigation("SliderTexts");
                });
#pragma warning restore 612, 618
        }
    }
}
